added email starter
0xsequence/sequence-cli pull request #14
Opened 2024-09-25 13:56 UTC by moskalyk

2024-09-25 21:41 UTC, RichardIrala commented on src/boilerplates/boilerplates.ts
> +
Remove the indentation within each .option to maintain consistency with the other commands

2024-09-25 21:43 UTC, RichardIrala commented
* You should add the new command to readme.md
* The command works well

2024-09-26 10:42 UTC, taylanpince requested changes
README + Richard's comment as well

2024-09-26 16:47 UTC, RichardIrala approved these changes

2024-09-26 16:48 UTC, RichardIrala approved these changes

2024-09-26 19:38 UTC, taylanpince approved these changes

2024-09-26 19:39 UTC, merged