added google auth project
0xsequence/sequence-cli pull request #15
Opened 2024-09-25 14:05 UTC by moskalyk

2024-09-25 21:45 UTC, RichardIrala commented on src/boilerplates/boilerplates.ts
> +        )
Remove the indentation within each .option to maintain consistency with the other commands

2024-09-25 21:49 UTC, RichardIrala commented
* You should add the new command to readme.md
* The command works well

2024-09-26 10:42 UTC, taylanpince requested changes
Looks good, let's add to README and make the update for @RichardIrala 's comment about indentation

2024-09-26 16:52 UTC, RichardIrala approved these changes, later dismissed

2024-09-26 19:39 UTC, taylanpince submitted a review, later dismissed

2024-09-26 19:40 UTC, taylanpince approved these changes

2024-09-26 19:40 UTC, merged